### ISSUE TITLE
Use the actual UUIDv4 format

### ISSUE THREAD

**Issue by gprst** [janlelis/yyid.js#3]
Hi, according to [Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format), a UUID is not mere series of random numbers ; a valid UUIDv4 is as follows :

> xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx
>
> The four-bit M and the 1 to 3 bit N fields code the format of the UUID itself.

M represents the UUID version, so is supposed to be `4` here, and N the UUID variant (I don't know much more about that).

**Comment by gprst** [comment]
It seems that `N` is supposed to be one of `8`, `9`, `a`, `b`, according to [Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Variants) again (these values are for a variant 1 UUID, as variant 0 is legacy and variant 2 is reserved by Microsoft).

**Comment by janlelis** [comment]
This is intentional, but I must admit, this is not clear from the README.

The idea is that the library generates (cryptographically secure) random ids, similar to type 4-uuids, but generates even more randomness with the same byte size (at least in hex-string notation. one could of cause optimize away the static bits of the id, this is where yyids and uuids are not compatible).

**Comment by janlelis** [comment]
Leaving this open as a reminder to improve the README
